name: timetable
description: Mini project with Flask backend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_icons: ^1.1.0
  bubble_tab_indicator: "^0.1.4"
  flutter_svg: ^0.22.0
  syncfusion_flutter_calendar: ^19.1.66

  http: ^0.13.3
  dio: ^4.0.0
  provider: ^5.0.0

  intl: ^0.17.0
  file_picker: ^3.0.2+2
  path: ^1.8.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
